services:
  db:
    image: postgres:18.0
    restart: unless-stopped
    env_file: .env
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

  mongodb:
    image: mongo:8.2
    restart: unless-stopped
    env_file: .env
    ports:
      - '${MONGODB_PORT:-27017}:27017'
